version: "3"

volumes:
  travel_db:

services:
  travel-web:
    container_name: travel-web
    build:
      context: ./web
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 80:80

  travel-parser-js:
    container_name: travel-parser-js
    build:
      context: .
      dockerfile: Dockerfile
    env_file: 
      - .env
    restart: unless-stopped
    ports:
      - 3000
    volumes:
      - travel_db:/:/src/database/