name: Main CI

on:
  push:
    branches:
      - 'main'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn install
    - name: Run ESLint
      run: yarn run lint

  push-to-ghcr:
    runs-on: ubuntu-latest
    needs:
      - lint
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_PAT }}
      - name: Build and push to GHCR
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ghcr.io/bbalkonsky/travel-parser-js:${{ github.sha }}
            ghcr.io/bbalkonsky/travel-parser-js:latest

  deploy:
    runs-on: ubuntu-latest
    needs: 
      - push-to-ghcr
    env:
      DEPLOY_URL: ${{ secrets.DEPLOY_URL }}
    steps:
      - name: Hook to server
        run: curl "https://${{ env.DEPLOY_URL }}/travel-parser-js"