FROM nginx:1.23.0
LABEL org.opencontainers.image.authors="A-styler@ya.ru"
LABEL org.opencontainers.image.source="https://github.com/bbalkonsky/travel-parser-js.git"

COPY ./index.html /usr/share/nginx/html/index.html
COPY ./script.js /usr/share/nginx/html/script.js